
#* 1. Start with Operating System(OS)
#* 2. Install Node 
#* 3. Copy app files 
#* 4. Run node app.js  




FROM node:alpine

COPY . /app 

WORKDIR /app 


CMD node /app.js   
# * CMD node app/app.js 



